{% set version = "0.0.0.2023.06.25" %}
{% set llvm_version = "16.0.6" %}

package:
  name: clspv
  version: {{ version }}

source:
  - url: https://github.com/google/clspv/archive/cba2664375f8f134552b3d03f267e43243901873.tar.gz
    sha256: 260a35b9b05128fffedb9aaee892b1a5c6654fada4afa8a2bb0a18021aea3260
    patches:
      - patches/0001-LLVM-16-fixes.patch
      - patches/0002-Fix-cmake-build.patch

  # Need the sources matching the binary version we install from conda
  - url: https://github.com/llvm/llvm-project/releases/download/llvmorg-{{ llvm_version }}/llvm-project-{{ llvm_version }}.src.tar.xz
    sha256: ce5e71081d17ce9e86d7cbcfa28c4b04b9300f8fb7e78422b1feb6bc52c3028e
    folder: llvm

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - python >=3
  host:
    - llvmdev  {{ llvm_version }}
    - clangdev {{ llvm_version }}
    - llvm     {{ llvm_version }}
    - libclang-cpp  {{ llvm_version }}
    - spirv-tools
    - spirv-headers
    - zlib

test:
  commands:
    - test -f ${PREFIX}/bin/clspv
    - clspv --help

about:
  home: https://github.com/google/clspv
  dev_url: https://github.com/google/clspv
  license: MIT AND BSD-3-Clause AND Apache-2.0 WITH LLVM-exception
  license_file:
    - LICENSE
    - llvm/llvm/LICENSE.TXT
  license_family: Apache
  summary: Clspv is a prototype compiler for a subset of OpenCL C to Vulkan compute shaders.

extra:
  recipe-maintainers:
    - isuruf
  feedstock-name: clspv
